# Generated by Django 4.1.6 on 2023-08-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="is_visible",
            new_name="public",
        ),
    ]
