# Generated by Django 4.1.6 on 2023-07-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="description",
            new_name="summary",
        ),
        migrations.RemoveField(
            model_name="book",
            name="download_count",
        ),
    ]
