# Generated by Django 4.1.6 on 2023-08-18 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_book_slug_genre_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-posted_at"]},
        ),
        migrations.RemoveField(
            model_name="book",
            name="store_url",
        ),
        migrations.AddField(
            model_name="book",
            name="users_like",
            field=models.ManyToManyField(
                blank=True, related_name="books_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
