# Generated by Django 4.1.6 on 2023-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_rename_description_book_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
