# Generated by Django 4.1.6 on 2023-08-17 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0004_alter_book_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_book",
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Favorite",
            new_name="Saved",
        ),
        migrations.DeleteModel(
            name="FavoriteBook",
        ),
        migrations.AddField(
            model_name="savedbook",
            name="saved",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_book",
                to="books.saved",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedbook",
            unique_together={("saved", "book")},
        ),
    ]
