# Generated by Django 4.1.6 on 2023-08-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_options_remove_book_store_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="summary",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="cover",
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
    ]
