# Generated by Django 4.1.6 on 2023-08-28 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0006_delete_genre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saved",
            options={"ordering": ["-at"]},
        ),
        migrations.AddField(
            model_name="book",
            name="saved_books",
            field=models.ManyToManyField(
                blank=True,
                related_name="books_saved",
                through="books.Saved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saved",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="saved",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="SavedBook",
        ),
    ]
