# Generated by Django 4.1.6 on 2023-08-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_saved_options_book_saved_books_saved_book_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="saved_books",
        ),
        migrations.DeleteModel(
            name="Saved",
        ),
    ]
