INSERT INTO
 books_genre (id,name)
  VALUES
(1,'Academic'),
(2,'Action and Adventure'),
(3,'Anthology'),
(4,'Art'),
(5,'Autobiography'),
(6,'Biography'),
(7,'Children''s'),
(8,'Comics and Graphic Novels'),
(9,'Cookbook'),
(10, 'Crime and Detective'),
(11, 'Drama'),
(12, 'Encyclopedia'),
( 13,'Erotica'),
( 14,'Essay'),
( 15,'Fantasy'),
(16, 'Guide'),
(17, 'Health and Fitness'),
( 18,'Historical Fiction'),
(19, 'History'),
(20, 'Horror'),
(21, 'Humor'),
(22, 'Journal'),
(23, 'Memoir'),
(24, 'Mystery'),
(25, 'Nature and Environment'),
(26, 'Paranormal and Supernatural'),
(27, 'Philosophy'),
(28, 'Poetry'),
(29, 'Politics and Current Affairs'),
(30, 'Psychology'),
(31, 'Religion and Spirituality'),
(32, 'Romance'),
(33, 'Satire'),
(34, 'Science'),
(35, 'Science Fiction'),
(36,'Self-Help'),
(37,'Short Stories'),
(38,'Social Science'),
(39,'Sports and Recreation'),
(40,'Thriller'),
(41,'Travel'),
(42,'True Crime'),
(43,'War and Military'),
(44,'Western'),
(45,"Women's Fiction"),
(46,'Writing and Language'),
(47,'Young Adult'),
(48,'Fantasy Romance'),
(49,'Historical Romance'),
(50,'Contemporary Romance');