# Generated by Django 4.1.6 on 2023-08-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_contact_customuser_following_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Network",
        ),
        migrations.RenameIndex(
            model_name="network",
            new_name="accounts_ne_created_9df718_idx",
            old_name="accounts_co_created_07cffc_idx",
        ),
    ]
